import 'package:ticket_booking/model/seat_item_model.dart';

List<SeatItemModel> seatItems = [
  SeatItemModel(id: 1, seatNumber: 'A-1', isSelected: false),
  SeatItemModel(id: 2, seatNumber: 'A-2', isSelected: false),
  SeatItemModel(id: 3, seatNumber: 'A-3', isSelected: false),
  SeatItemModel(id: 4, seatNumber: 'A-4', isSelected: false),
  SeatItemModel(id: 5, seatNumber: 'B-1', isSelected: false),
  SeatItemModel(id: 6, seatNumber: 'B-2', isSelected: false),
  SeatItemModel(id: 7, seatNumber: 'B-3', isSelected: false),
  SeatItemModel(id: 8, seatNumber: 'B-4', isSelected: false),
  SeatItemModel(id: 9, seatNumber: 'C-1', isSelected: false),
  SeatItemModel(id: 10, seatNumber: 'C-2', isSelected: false),
  SeatItemModel(id: 11, seatNumber: 'C-3', isSelected: false),
  SeatItemModel(id: 12, seatNumber: 'C-4', isSelected: false),
  SeatItemModel(id: 13, seatNumber: 'D-1', isSelected: false),
  SeatItemModel(id: 14, seatNumber: 'D-2', isSelected: false),
  SeatItemModel(id: 15, seatNumber: 'D-3', isSelected: false),
  SeatItemModel(id: 16, seatNumber: 'D-4', isSelected: false),
  SeatItemModel(id: 17, seatNumber: 'E-1', isSelected: false),
  SeatItemModel(id: 18, seatNumber: 'E-2', isSelected: false),
  SeatItemModel(id: 19, seatNumber: 'E-3', isSelected: false),
  SeatItemModel(id: 20, seatNumber: 'E-4', isSelected: false),
  SeatItemModel(id: 21, seatNumber: 'F-1', isSelected: false),
  SeatItemModel(id: 22, seatNumber: 'F-2', isSelected: false),
  SeatItemModel(id: 23, seatNumber: 'F-3', isSelected: false),
  SeatItemModel(id: 24, seatNumber: 'F-4', isSelected: false),
  SeatItemModel(id: 25, seatNumber: 'G-1', isSelected: false),
  SeatItemModel(id: 26, seatNumber: 'G-2', isSelected: false),
  SeatItemModel(id: 27, seatNumber: 'G-3', isSelected: false),
  SeatItemModel(id: 28, seatNumber: 'G-4', isSelected: false),
  SeatItemModel(id: 29, seatNumber: 'H-1', isSelected: false),
  SeatItemModel(id: 30, seatNumber: 'H-2', isSelected: false),
  SeatItemModel(id: 31, seatNumber: 'H-3', isSelected: false),
  SeatItemModel(id: 32, seatNumber: 'H-4', isSelected: false),
  SeatItemModel(id: 33, seatNumber: 'I-4', isSelected: false),
  SeatItemModel(id: 34, seatNumber: 'I-2', isSelected: false),
  SeatItemModel(id: 35, seatNumber: 'I-3', isSelected: false),
  SeatItemModel(id: 36, seatNumber: 'I-4', isSelected: false),
];
